import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c8c6c6",
        "secondary-container": "#e0e5cc",
        "on-error": "#ffffff",
        "on-primary-container": "#9c9b9b",
        "surface-container-high": "#eae9d5",
        "inverse-on-surface": "#f3f2dd",
        "on-surface-variant": "#444748",
        "tertiary-fixed": "#e6e2da",
        "on-secondary-fixed": "#191d0e",
        "secondary-fixed": "#e0e5cc",
        "on-primary": "#ffffff",
        "tertiary-container": "#34332e",
        "error-container": "#ffdad6",
        "surface-bright": "#fbfae6",
        "surface-container": "#f0efda",
        "on-background": "#1b1d10",
        "on-tertiary-container": "#9e9b94",
        surface: "#fbfae6",
        "on-primary-fixed": "#1b1c1c",
        "on-primary-fixed-variant": "#474747",
        secondary: "#5c614d",
        "on-tertiary-fixed": "#1c1c17",
        "on-secondary": "#ffffff",
        primary: "#1e1e1e",
        "surface-tint": "#5f5e5e",
        "inverse-primary": "#c8c6c6",
        "outline-variant": "#c4c7c7",
        "surface-container-highest": "#e4e4cf",
        error: "#ba1a1a",
        "on-secondary-container": "#626753",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c4c9b1",
        outline: "#747878",
        "tertiary-fixed-dim": "#c9c6bf",
        "on-surface": "#1b1d10",
        "surface-container-low": "#f5f5e0",
        "on-error-container": "#93000a",
        background: "#fbfae6",
        "on-secondary-fixed-variant": "#444937",
        tertiary: "#1f1e19",
        "surface-dim": "#dcdbc7",
        "primary-fixed": "#e4e2e1",
        "primary-container": "#333333",
        "inverse-surface": "#303124",
        "surface-variant": "#e4e4cf",
        "on-tertiary-fixed-variant": "#484741",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "24px",
        "container-max": "1280px",
        gutter: "32px",
        unit: "8px",
        "section-gap": "120px",
      },
      fontFamily: {
        bodoni: ["var(--font-bodoni)", "Georgia", "serif"],
        work: ["var(--font-work)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" },
        ],
      },
      animation: {
        marquee: "marquee 40s linear infinite",
        "fade-in": "fadeIn 0.8s ease-out forwards",
        "zoom-in": "zoomIn 20s infinite alternate",
        bounce: "bounce 2s infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        zoomIn: {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(1.15)" },
        },
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
